alibaba/CicadaPlayer

.travis.yml
build_tools/ffmpeg_commands.sh
external/build_external.sh
external/contribute/ffmpeg/0004-chore-fix-Linux-build.patch

chore: add travis for Linux

---

.travis.yml
README.md
cmdline/CMakeLists.txt
framework/cacheModule/CMakeLists.txt
framework/code_coverage.cmake
framework/codec/CMakeLists.txt
framework/data_source/CMakeLists.txt
framework/demuxer/CMakeLists.txt
framework/filter/CMakeLists.txt
framework/muxer/CMakeLists.txt
framework/render/CMakeLists.txt
framework/tests/CMakeLists.txt
framework/tests/dataSource/CMakeLists.txt
framework/tests/decoder/CMakeLists.txt
framework/tests/decoder/decoderUnitTest.cpp
framework/tests/demuxer/CMakeLists.txt
framework/tests/render/CMakeLists.txt
mediaPlayer/CMakeLists.txt

test: support codecov

---

framework/tests/CMakeLists.txt
framework/tests/render/renderTest.cpp

test: enable render test on Travis

---

mediaPlayer/tests/CMakeLists.txt
mediaPlayer/tests/mediaPlayerTest.cpp
mediaPlayer/tests/mediaPlayerTest.h
mediaPlayer/tests/mediaPlayerUnitTest.cpp
mediaPlayer/tests/player_command.cpp
mediaPlayer/tests/player_command.h

test: add more mediaplayer tests

---

mediaPlayer/tests/mediaPlayerTest.cpp
mediaPlayer/tests/player_command.cpp

test: fix compile

---

framework/base/media/IAFPacket.h
framework/cacheModule/CacheManager.cpp
framework/cacheModule/CacheManager.h
framework/cacheModule/CacheModule.cpp
framework/cacheModule/CacheModule.h
framework/cacheModule/cache/CacheFileRemuxer.cpp
framework/cacheModule/cache/CacheFileRemuxer.h
framework/demuxer/avFormatDemuxer.cpp
framework/demuxer/avFormatDemuxer.h
mediaPlayer/ICicadaPlayer.h
mediaPlayer/MediaPlayer.cpp
mediaPlayer/MediaPlayer.h
mediaPlayer/PlayerCacheDataSource.cpp
mediaPlayer/PlayerCacheDataSource.h
mediaPlayer/SuperMediaPlayer.cpp
mediaPlayer/media_player_api.cpp
mediaPlayer/native_cicada_player_def.h

1. send media frame by reference
2. support the callback

support send media frame with more info

---

doc/compile_ios.md

docs: improve ios compile doc

---

mediaPlayer/tests/CMakeLists.txt
mediaPlayer/tests/apiTest/mediaPlayerApiTest.cpp
mediaPlayer/tests/formatTest/mediaPlayerFormatTest.cpp
mediaPlayer/tests/mediaPlayerTest.cpp
mediaPlayer/tests/mediaPlayerTest.h
mediaPlayer/tests/player_command.cpp
mediaPlayer/tests/player_command.h
mediaPlayer/tests/seekTest/mediaPlayerSeekTest.cpp
mediaPlayer/tests/switch_stream/CMakeLists.txt
mediaPlayer/tests/switch_stream/mediaPlayerSwitchStream.cpp

test(mediaPlayer): add mediaPlayerSwitchStream test

---

mediaPlayer/tests/CMakeLists.txt
mediaPlayer/tests/apiTest/mediaPlayerApiTest.cpp
mediaPlayer/tests/cache/CMakeLists.txt
mediaPlayer/tests/cache/mediaPlayerCacheTest.cpp
mediaPlayer/tests/formatTest/mediaPlayerFormatTest.cpp
mediaPlayer/tests/mediaPlayerTest.cpp
mediaPlayer/tests/mediaPlayerTest.h
mediaPlayer/tests/seekTest/mediaPlayerSeekTest.cpp
mediaPlayer/tests/switch_stream/mediaPlayerSwitchStream.cpp

test(mediaPlayer): add  cache test

---

framework/render/video/IVideoRender.h
mediaPlayer/MediaPlayerConfig.cpp
mediaPlayer/MediaPlayerConfig.h
mediaPlayer/tests/apiTest/mediaPlayerApiTest.cpp

test(mediaPlayer): add more api test

---

mediaPlayer/tests/formatTest/mediaPlayerFormatTest.cpp

test(mediaPlayer): add ext subtitle test

---

mediaPlayer/tests/cache/mediaPlayerCacheTest.cpp

test(mediaPlayer): add cached source test

---

framework/base/media/IAFPacket.h

framework(IAFPacket): operator== not care nb_samples

---

framework/demuxer/avFormatDemuxer.cpp

fix(avFormatDemuxer): can play concat

---

.travis.yml
CMakeLists.txt
cmdline/CMakeLists.txt
framework/cacheModule/CacheManager.cpp
framework/cacheModule/CacheModule.cpp
framework/tests/CMakeLists.txt
framework/tests/dataSource/CMakeLists.txt
framework/tests/dataSource/dataSourceUnitTest.cpp
framework/tests/decoder/CMakeLists.txt
framework/tests/demuxer/CMakeLists.txt
framework/tests/render/CMakeLists.txt
mediaPlayer/tests/apiTest/CMakeLists.txt
mediaPlayer/tests/apiTest/mediaPlayerApiTest.cpp
mediaPlayer/tests/cache/CMakeLists.txt
mediaPlayer/tests/formatTest/CMakeLists.txt
mediaPlayer/tests/player_command.cpp
mediaPlayer/tests/player_command.h
mediaPlayer/tests/seekTest/CMakeLists.txt
mediaPlayer/tests/switch_stream/CMakeLists.txt
mediaPlayer/tests/switch_stream/mediaPlayerSwitchStream.cpp

test: enable asan on travis

---

mediaPlayer/SuperMediaPlayer.cpp

make sure stream is opened before get meta

fix(SuperMediaPlayer): fix crash in setup av path

---

framework/demuxer/avFormatDemuxer.cpp

1. add protection
2. reduce cpu usage

fix(demuxer): reduce cpu usage when need retry

---

framework/demuxer/play_list/HLSManager.cpp

fix(HLSManager): first seek video or mix steam

---

mediaPlayer/SuperMediaPlayer.cpp

fix(drop): compare position to seekPos

---

external/build_external.sh
external/contribute/ffmpeg/0006-flv-add-extensions-for-H.265-HEVC.patch

feat(external): flv support hevc

---

framework/codec/ActiveDecoder.cpp
framework/demuxer/avFormatDemuxer.cpp
framework/demuxer/avFormatDemuxer.h

fix(ActiveDecoder): drop logic effective hevc only

---

mediaPlayer/player_msg_control.cpp

fix(player_msg_control): add lock

---

mediaPlayer/media_packet_queue.cpp

fix(media_packet_queue): fix get key frame logic

---

framework/codec/Apple/AppleVideoToolBox.cpp

fix(AppleVideoToolBox): fix reorder hevc pts

---

mediaPlayer/tests/formatTest/mediaPlayerFormatTest.cpp

test(mediaPlayer): disable flv live test

---

.travis.yml
cmdline/CMakeLists.txt
mediaPlayer/tests/apiTest/CMakeLists.txt
mediaPlayer/tests/cache/CMakeLists.txt
mediaPlayer/tests/formatTest/CMakeLists.txt
mediaPlayer/tests/seekTest/CMakeLists.txt
mediaPlayer/tests/switch_stream/CMakeLists.txt

chore(tests): fix mediaplayer test build on macOS

---

framework/codec/Apple/AppleVideoToolBox.cpp

fix(AppleVideoToolBox): fix dead lock when bg

---

framework/codec/ActiveDecoder.cpp
framework/codec/ActiveDecoder.h
framework/codec/Apple/AppleVideoToolBox.cpp
mediaPlayer/SuperMediaPlayer.cpp
mediaPlayer/SuperMediaPlayer.h

(cherry picked from commit b96a6918cbabae7e05a5ff000f6a4515f4bd0825)

refactor(decoder): reduce memory for recover iOS playback

---

framework/demuxer/avFormatDemuxer.h
framework/filter/ffmpegAudioFilter.h
framework/utils/af_clock.h
framework/utils/ringBuffer.cpp
mediaPlayer/SuperMediaPlayer.h
mediaPlayer/analytics/AnalyticsCollectorImpl.h

chore(Android): fix android build use ndk 14b

---

framework/codec/ActiveDecoder.cpp
framework/codec/ActiveDecoder.h
framework/codec/avcodecDecoder.cpp

perf(ActiveDecoder): speedup lock usage

---

cmdline/cicadaPlayer.cpp

chore(cmdline): improve code

---

build_player.sh

chore(demo): disable build ipa in packet_iOS

---

framework/demuxer/HLSSupport.md

docs: update HLS Support instructions

---

framework/data_source/curl/CURLConnection.cpp
framework/data_source/curl/CURLConnection.h
framework/data_source/curl/curl_data_source.cpp

fix(data_source): update CURLConnection filesize with new url

---

framework/codec/Apple/AppleVideoToolBox.cpp
framework/codec/Apple/AppleVideoToolBox.h

fix(codec): fix err in backgroud recoverage vtb

---

framework/cacheModule/cache/CacheFileRemuxer.cpp
framework/cacheModule/cache/CacheFileRemuxer.h
framework/muxer/IMuxer.h
framework/muxer/IMuxerPrototype.cpp
framework/muxer/IMuxerPrototype.h
framework/muxer/ffmpegMuxer/FfmpegMuxer.cpp
framework/muxer/ffmpegMuxer/FfmpegMuxer.h

style(muxer): change DataType name and namespace

---

framework/utils/Md5Utils.cpp
framework/utils/Md5Utils.h

refactor(framework): add sha256 utils

---

framework/tests/dataSource/dataSourceUnitTest.cpp
framework/tests/decoder/decoderUnitTest.cpp
framework/tests/demuxer/demuxerUnitTest.cpp
framework/tests/render/renderTest.cpp
framework/utils/AFUtils.c
framework/utils/AFUtils.h
mediaPlayer/tests/apiTest/mediaPlayerApiTest.cpp
mediaPlayer/tests/cache/mediaPlayerCacheTest.cpp
mediaPlayer/tests/formatTest/mediaPlayerFormatTest.cpp
mediaPlayer/tests/seekTest/mediaPlayerSeekTest.cpp
mediaPlayer/tests/switch_stream/mediaPlayerSwitchStream.cpp

test(mediaPlayer): ignore sigpip

---

build_tools/build_iOS.sh
build_tools/build_native.sh

chore(build_tools): use MinSizeRel config to build apple framework

---

build_tools/build_native.sh

Travis use uname -m get a 0...

chore(build_tools): fix travis build

---

build_tools/build_iOS.sh
build_tools/build_native.sh
build_tools/common_build.sh
build_tools/gen_build_version.sh
build_tools/iOS/CMakeLists.txt
build_tools/src/build_version.cpp

feat(build_tools): add build version print in shared lib

---

external/build_external.sh

build(external): use $CICADA_FFMPEG_CONFIG_FILE  ffmpeg config file

---

.travis.yml

ci: add clang format check

---

framework/codec/Apple/video_tool_box_utils.c
framework/codec/Apple/video_tool_box_utils.h

refactor(video_tool_box_utils): delet no usage function

---

framework/demuxer/avFormatDemuxer.cpp

fix(avformatdemuxer): reset the avio status after interrupt

---

mediaPlayer/SuperMediaPlayer.cpp

fix(supermediaplayer): restart the audio render on create

---

external/player_git_source_list.sh

chore(external): openssl use OpenSSL_1_1_1f tag instead of branch

---

mediaPlayer/MediaPlayer.cpp
mediaPlayer/MediaPlayer.h
mediaPlayer/SuperMediaPlayer.cpp
mediaPlayer/native_cicada_player_def.h
mediaPlayer/player_notifier.cpp
mediaPlayer/player_notifier.h

(cherry picked from commit fecf86aede52961fc9f79f3643b84b31e1faa5b4)
#	mediaPlayer/MediaPlayer.cpp

fix(cache): stop cache when seek in cache

---

cmdline/IEventReceiver.h
cmdline/NetWorkEventReceiver.cpp
cmdline/SDLEventReceiver.cpp
cmdline/cicadaEventListener.cpp
cmdline/cicadaEventListener.h

feat(cmdline): add percentage seek

---

framework/render/audio/Android/AudioTrackRender.h

(cherry picked from commit c7a638deb39269e0186291a6d24300604571c213)

fix(audioTrackRender): complie error

---

mediaPlayer/SuperMediaPlayer.cpp

fix(supermediaplayer): use sync video pts to detect pts revert

---

mediaPlayer/SuperMediaPlayer.cpp
mediaPlayer/SuperMediaPlayer.h

#	mediaPlayer/SuperMediaPlayer.h

fix: check audio EOS work around

---

framework/codec/Apple/AppleVideoToolBox.cpp
framework/codec/Apple/AppleVideoToolBox.h

(cherry picked from commit af7068ed2bea81210388e680e334aab664703546)

improvement(vtb): disable poc reorder when there are too much error

---

CMakeLists.txt
cmdline/CMakeLists.txt
framework/code_coverage.cmake
framework/tests/GoogleTest.cmake
framework/tests/dataSource/CMakeLists.txt
framework/tests/decoder/CMakeLists.txt
framework/tests/demuxer/CMakeLists.txt
mediaPlayer/tests/apiTest/CMakeLists.txt
mediaPlayer/tests/cache/CMakeLists.txt
mediaPlayer/tests/formatTest/CMakeLists.txt
mediaPlayer/tests/seekTest/CMakeLists.txt
mediaPlayer/tests/switch_stream/CMakeLists.txt

chore: improve cmake file

---

framework/data_source/curl/CURLConnection.cpp

improvement(curl): enable SSL VERIFYHOST

---

framework/demuxer/avFormatDemuxer.cpp

refactor(avFormatDemuxer): keep the error on read

---

framework/data_source/ffmpeg_data_source.cpp

improvement(ffmpeg_data_source): support read timeout

---

mediaPlayer/ICicadaPlayer.h
mediaPlayer/MediaPlayer.cpp
mediaPlayer/MediaPlayer.h
mediaPlayer/SuperMediaPlayer.cpp
mediaPlayer/media_player_api.cpp
mediaPlayer/media_player_api.h
mediaPlayer/native_cicada_player_def.h

feat(mediaplayer): add setClockRefer api

---

mediaPlayer/SuperMediaPlayer.cpp

fix(mediaplayer): fix miss out start message

---

external/player_git_source_list.sh

build(openssl): update to OpenSSL_1_1_1g

---

.gitignore
CMakeLists.txt
cmdline/CMakeLists.txt
doc/compile_mac.md
framework/macOSX.cmake

build(cmdline): support build cmdline use Xcode

---

mediaPlayer/SuperMediaPlayer.cpp

This reverts commit cc7942f54dd32f2c12aaf3077088e04e2205360c.

Revert "fix(mediaplayer): fix maybe crash on stop"
